services:
  db:
    image: postgres:16-alpine
    container_name: salesmanship_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: salesmanship
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d salesmanship"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: salesmanship_api
    environment:
      PORT: 8080
      JWT_SECRET: supersecretjwtkey123!
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: secretpassword
      DB_NAME: salesmanship
      DB_SSLMODE: disable
      DB_TIMEZONE: Asia/Jakarta
      SEED_DB: "true"
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  nginx:
    image: nginx:alpine
    container_name: salesmanship_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api

volumes:
  pgdata:
